fix: crash with InvalidAuthBlockingTokenError (wrong audience)
firebase/firebase-functions-python pull request #145
Opened 2023-10-09 08:48 UTC by exaby73

2023-10-09 09:55 UTC, russellwheatley requested changes

2023-10-09 09:55 UTC, russellwheatley commented on src/firebase_functions/private/_identity_fn.py
> +        last_sign_in_time = _dt.datetime.utcfromtimestamp(int(token_data["last_sign_in_time"]) / 1000.0)
```suggestion
        last_sign_in_time = _dt.datetime.utcfromtimestamp(int(token_data["last_sign_in_time"] / 1000.0 ))
```
Think it should be this.

2023-10-09 09:57 UTC, russellwheatley approved these changes
LGTM

2023-10-10 11:53 UTC, exaby73 commented
Lint error will be fixed on merge of https://github.com/firebase/firebase-functions-python/pull/147

2023-10-10 12:11 UTC, Salakar approved these changes

2023-10-10 20:17 UTC, taeold commented
Before I merge - can you fix the linter issues?

2023-10-13 09:20 UTC, EmilioNicolas commented
Hi! When can we expect this issue merged and deployed? thanks!!

2023-10-16 21:55 UTC, merged

2023-10-23 09:56 UTC, EmilioNicolas commented
Hi! Is it already in PRO? should we wait to other release?

2023-10-24 09:27 UTC, exaby73 commented
This should be fixed in 0.1.2, which hasn't been released yet, but will be soon