fix: incorrect type for document snapshop in Firestore auth triggers
firebase/firebase-functions-python pull request #212
Opened 2024-07-03 02:28 UTC by exaby73

2024-07-03 08:41 UTC, cabljac requested changes
lgtm but is the print statement meant to be left in?

2024-07-03 08:41 UTC, cabljac commented on src/firebase_functions/firestore_fn.py
> +    print(f"Event type: {event_type}")
Do we need this log?

2024-07-09 05:31 UTC, exaby73 commented on src/firebase_functions/firestore_fn.py
> +    print(f"Event type: {event_type}")
Thanks for that catch

2024-07-09 07:08 UTC, cabljac approved these changes

2024-07-12 13:55 UTC, merged